let dishes = [{
    "name": "Pizza Margherita",
    "description": "mit natürlicher Tomatensauce und 100% Mozzarella",
    "image": "img/1.png",
    'type': 'salad',
    "price": 7.50,
    "amount": 1,
    "endsum": 7.50,
},
{
    "name": "Pizza Veggie Deluxe",
    "description": "mit roten Zwiebeln, Paprika, Champignons, Spinat, Broccoli, Chili-Gewürz und extra Mozzarella",
    "image": "img/1.png",
    'type': 'pizza',
    "price": 9.50,
    "amount": 1,
    "endsum": 9.50,
},
{
    "name": "Pizza BBQ-Chicken",
    "description": "mit Barbecuesauce anstelle von Tomatensauce, Mozzarella, Zwiebeln, Paprika, Hähnchenbrustfilet, Mais und Knoblauchöl auf dem Pizzarand",
    "image": "img/1.png",
    'type': 'salad',
    "price": 10.50,
    "amount": 1,
    "endsum": 10.50,
},
{
    "name": "Pizza Four Cheese",
    "description": "mit Creme Fraiche, Mozzarella, rotem Cheddar, holländischem Gouda, Gorgonzola und Knoblauchöl auf dem Pizzarand",
    "image": "img/1.png",
    'type': 'pizza',
    "price": 9.50,
    "amount": 1,
    "endsum": 9.50,
},
{
    "name": "Pizza Spinaci",
    "description": "mit Tomatensauce, Spinat und Knoblauch",
    "image": "img/1.png",
    'type': 'salad',
    "price": 9.50,
    "amount": 1,
    "endsum": 9.50,
},
{
    "name": "Pizza Sucuk",
    "description": "mit Knoblauchwurst, roten Zwiebeln und Jalapenos",
    "image": "img/1.png",
    'type': 'pizza',
    "price": 10.50,
    "amount": 1,
    "endsum": 10.50,
},
{
    "name": "Pizza 4 Formaggi",
    "description": "mit 4 Käsesorten",
    "image": "img/1.png",
    'type': 'salad',
    "price": 11.50,
    "amount": 1,
    "endsum": 11.00,
},
];